/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.Im', null, global);
goog.exportSymbol('proto.ImType', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Im = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Im, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Im.displayName = 'proto.Im';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Im.prototype.toObject = function(opt_includeInstance) {
  return proto.Im.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Im} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Im.toObject = function(includeInstance, msg) {
  var f, obj = {
    imtype: jspb.Message.getField(msg, 1),
    senderid: jspb.Message.getField(msg, 2),
    sendername: jspb.Message.getField(msg, 3),
    roomid: jspb.Message.getField(msg, 4),
    content: jspb.Message.getField(msg, 5)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Im}
 */
proto.Im.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Im;
  return proto.Im.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Im} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Im}
 */
proto.Im.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ImType} */ (reader.readEnum());
      msg.setImtype(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSenderid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendername(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRoomid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Im.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Im.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Im} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Im.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.ImType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * required ImType imType = 1;
 * @return {!proto.ImType}
 */
proto.Im.prototype.getImtype = function() {
  return /** @type {!proto.ImType} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/** @param {!proto.ImType} value */
proto.Im.prototype.setImtype = function(value) {
  jspb.Message.setField(this, 1, value);
};


proto.Im.prototype.clearImtype = function() {
  jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Im.prototype.hasImtype = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional uint32 senderid = 2;
 * @return {number}
 */
proto.Im.prototype.getSenderid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Im.prototype.setSenderid = function(value) {
  jspb.Message.setField(this, 2, value);
};


proto.Im.prototype.clearSenderid = function() {
  jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Im.prototype.hasSenderid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string sendername = 3;
 * @return {string}
 */
proto.Im.prototype.getSendername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.Im.prototype.setSendername = function(value) {
  jspb.Message.setField(this, 3, value);
};


proto.Im.prototype.clearSendername = function() {
  jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Im.prototype.hasSendername = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 roomid = 4;
 * @return {number}
 */
proto.Im.prototype.getRoomid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.Im.prototype.setRoomid = function(value) {
  jspb.Message.setField(this, 4, value);
};


proto.Im.prototype.clearRoomid = function() {
  jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Im.prototype.hasRoomid = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional string content = 5;
 * @return {string}
 */
proto.Im.prototype.getContent = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.Im.prototype.setContent = function(value) {
  jspb.Message.setField(this, 5, value);
};


proto.Im.prototype.clearContent = function() {
  jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Im.prototype.hasContent = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.ImType = {
  IMHANDSHAKE: 1,
  IMCHCLOSE: 2,
  SYSANNOUNCEMENT: 3,
  DANMAKU: 4,
  GIFT: 5
};

goog.object.extend(exports, proto);
